<a href="https://colab.research.google.com/github/sharmila-Nri/Python-mini-project-/blob/main/DATA_SET.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import random

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
datasetpath=('/content/drive/MyDrive/retail_transactions.csv')

In [ ]:
df=pd.read_csv(datasetpath)

In [ ]:
df

,TransactionID,TransactionDate,StoreID,CustomerID,ProductID,ProductCategory,Quantity,Price,PaymentType,Discount
0,T001,2024-01-01,102,1646,545,Electronics,1,150,Credit,15.0
1,T002,2024-01-02,103,1226,542,Toys,2,317,Debit,10.0
2,T003,2024-01-03,102,1515,593,Electronics,5,165,Debit,NaN
3,T004,2024-01-04,103,1793,560,Furniture,6,496,Debit,10.0
4,T005,2024-01-05,105,1864,523,Grocery,10,166,Debit,0.0
...,...,...,...,...,...,...,...,...,...,...
95,T096,2024-04-05,101,1918,559,Apparel,2,439,Cash,10.0
96,T097,2024-04-06,104,1190,579,Electronics,4,52,Debit,0.0
97,T098,2024-04-07,102,1932,504,Apparel,7,151,Credit,10.0
98,T099,2024-04-08,103,1285,587,Apparel,5,479,Credit,10.0
99,T100,2024-04-09,101,1602,574,Electronics,5,247,Credit,15.0

In [ ]:
df

,TransactionID,TransactionDate,StoreID,CustomerID,ProductID,ProductCategory,Quantity,Price,PaymentType,Discount
0,T001,2024-01-01,101.0,1190.0,523.0,Furniture,1.0,109.0,Debit,10.0
1,T002,2024-01-02,NaN,1245.0,565.0,NaN,NaN,120.0,NaN,NaN
2,T003,2024-01-03,NaN,1326.0,NaN,NaN,NaN,166.0,NaN,NaN
3,T004,2024-01-04,NaN,1396.0,NaN,NaN,NaN,170.0,NaN,NaN
4,T005,2024-01-05,NaN,1462.0,NaN,NaN,NaN,201.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
95,T096,2024-04-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,T097,2024-04-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,T098,2024-04-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,T099,2024-04-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,T100,2024-04-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
#Find the total revenue generated from all transactions
df['total_amount']=df['Quantity']*df['Price']
total_revenue=df['total_amount'].sum()
print("Total revenue: ₹",total_revenue)

Total revenue: ₹ 154794

In [13]:
#Identify the most frequently purchased product
most_frequent_purchased_product=df['ProductCategory'].mode()[0]
print("Most frequently purchased ProductCategory:",
      most_frequent_purchased_product)

Most frequently purchased ProductCategory: Furniture

In [14]:
#Calculate the average transaction amount
average_transaction_amount = df['total_amount'].mean()
print("Average Transaction Amount: ₹", average_transaction_amount)

Average Transaction Amount: ₹ 1547.94

In [15]:
#Filter transactions where the total amount is greater than ₹200
high_value_transactions = df[df['total_amount'] > 200]
print("High Value Transactions:\n", high_value_transactions)

High Value Transactions:
    TransactionID TransactionDate  StoreID  CustomerID  ProductID  \
1           T002      2024-01-02      103        1226        542
2           T003      2024-01-03      102        1515        593
3           T004      2024-01-04      103        1793        560
4           T005      2024-01-05      105        1864        523
5           T006      2024-01-06      103        1836        515
..           ...             ...      ...         ...        ...
95          T096      2024-04-05      101        1918        559
96          T097      2024-04-06      104        1190        579
97          T098      2024-04-07      102        1932        504
98          T099      2024-04-08      103        1285        587
99          T100      2024-04-09      101        1602        574

   ProductCategory  Quantity  Price PaymentType  Discount  total_amount
1             Toys         2    317       Debit      10.0           634
2      Electronics         5    165       Debit       NaN           825
3        Furniture         6    496       Debit      10.0          2976
4          Grocery        10    166       Debit       0.0          1660
5          Grocery         9    227       Debit       NaN          2043
..             ...       ...    ...         ...       ...           ...
95         Apparel         2    439        Cash      10.0           878
96     Electronics         4     52       Debit       0.0           208
97         Apparel         7    151      Credit      10.0          1057
98         Apparel         5    479      Credit      10.0          2395
99     Electronics         5    247      Credit      15.0          1235

[89 rows x 11 columns]

In [16]:
#Find the top 3 customers who have spent the most
customer_spending = df.groupby('CustomerID')['total_amount'].sum()
top_customers = customer_spending.nlargest(3)
print("Top 3 Customers by Spending:\n", top_customers)

Top 3 Customers by Spending:
 CustomerID
1734    5375
1396    4892
1532    4490
Name: total_amount, dtype: int64